### ISSUE TITLE
How to activate?

### ISSUE THREAD

**Issue by walhallaRV** [GetSimpleCMS-CE-plugins/plugin-EasyComments#1]
Hi,
this PlugIn would be interesting. But a very short "readme" or howto implement / activate the comments - option on a site would be great. Didn't get it running and have no more ideas what to try.

Thank you very much for any hint / help!

**Comment by risingisland** [comment]
Sorry for late reply.
Plugin has just been updated.
After install and activation, view options in Plugins sidebar.
hCaptcha has been added to avoid spammers. 
Just add `<?php easyComments();?>` to where you would like the comments sections to appear.
